# -*- coding: utf-8 -*-
"""Optimization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bu2rh5yWkCpz5JlkJR8TqueYz9y97rzy
"""

print('shashank')



#libraries
import math as m

#energy for wind turbine
v=float(input("Enter the wind speed in meter/second "))
r=float(input("Enter the radius of blade in metre"))
a=m.pi*(r**2)
cp=0.59 #Betz Limit
cg=float(input("enter the generator efficiency"))
nt=int(input("enter the no of winds turbine in one plant"))
rho=1.1906 
pw=0.5*rho*a*(v**3)*cp*cg*nt*2.7777*(10**(-7))

#environmental ascept
enw=7.5*(10**5) + 12*(10**7)*pw*365*24
#economical effect
ecw=1600*pw*365*24

print(pw)
print(enw)
print(ecw)

#for solar panel r is solar panel yield (%), H is annual average solar radiation on tilted panels and PR = Performan...


nefso=float(input("input efficiency of solar plant because of loss"))
AreaSo=float(input("input area of solar panel in m^2"))
RSo=float(input("solar panel yield %"))
PR=float(input("performance ratio"))
H=float(input("annual average solar radiation"))
Numberso=int(input("no of solar plates in one plant"))
pso=nefso*AreaSo*RSo*PR*H*Numberso*2.7777*(10**(-7))

#environmental ascept
enso=19*(10**5) + 40*(10**7)*pso*365*24
#economical effect
ecso=830*pso*365*24

print(pso)
print(enso)
print(ecso)

#for coal
mcoal=float(input("mass of coal used per second in tonnes"))
nefc=float(input("input efficiency of coal power plant"))
caf=float(input("input calorific value of coal in Mj/kg"))
pco=nefc*mcoal*caf*1000000*2.7777*(10**(-7))

#environmental ascept
enco=15*(10**5) + 1011.511*(10**7)*pco*365*24
#economical effect
ecco=3500*pco*365*24

print(pco)
print(enco)
print(ecco)

#for petroleum
mpet=float(input("litre of crude oil per second"))
nefp=float(input("input efficiency of oil plant"))
cafp=float(input("input calorific value of crude oil Mj/Kg"))
densitycrude=850
ppe=nefp*mpet*cafp*densitycrude*1000000*2.7777*(10**(-7))

#environmental ascept
enpe=15*(10**5) + 966.1517*(10**7)*ppe*365*24
#economical effect
ecpe=600*ppe*365*24

print(ppe)
print(enpe)
print(ecpe)

#for natural gas
mng=float(input("volume of natural gas in litre"))
nefng=float(input("input efficiency of natural gas plant"))
cafng=float(input("input calorific value of natural gas"))
densitygas=0.97
png=nefng*mng*densitygas*cafng*1000000*2.7777*(10**(-7))

#environmental ascept
enng=1*(10**5) + 412.7691*(10**7)*png*365*24
#economical effect
ecng=710*png*365*24

print(png)
print(enng)
print(ecng)

#for hydropower plant
height=float(input("height of hydroplant"))
area=float(input("enter area of plant"))
neffhydro=float(input("efficiency of hydroplant"))
phydro=neffhydro*1000*area*9.81*0.9*0.9*height*height*2.7777*(10**(-7))

#environmental ascept
enhydro=33*(10**5) + 24*(10**7)*phydro*365*24
#economical effect
echydro=2752*phydro*365*24

print(phydro)
print(enhydro)
print(echydro)

#nuclear
mnu=float(input("mass of nuclear fuel"))
nefnu=float(input("input efficiency of nuclear"))
cafnu=float(input("input calorific value of nuclear"))
pnu=nefnu*mnu*cafnu*2.7777*(10**(-7))*1000000

#environmental ascept
ennu=0.3*(10**5) + 12*(10**7)*pnu*365*24
#economical effect
ecnu=6000*pnu*365*24

print(pnu)
print(ennu)
print(ecnu)

#optimization functions
Power=pnu+phydro+png+ppe+pco+pw+pso
EnvironmentalFactor=ennu+enhydro+enng+enpe+enco+enw+enso
EconomicFactor=ecnu+echydro+ecng+ecpe+ecco+ecw+ecso

#constraints
preq=float(input("Input power requirement in lakh units for one year"))

Power1=-1*preq*(10**5)
pextra=float(input("storage capacity of power  in lakh units for one year"))

Power2=-1*pextra*(10**5)

print(Power1)

print(Power2)

!pip install pymoo

max=10**3

from pymoo.core.problem import ElementwiseProblem
from pymoo.core.variable import Real, Integer
class MultiObjectiveMixedVariableProblem(ElementwiseProblem):

    def __init__(self, **kwargs):
        vars = {
            "nnu": Integer(bounds=(0, max )),
            "nhydro": Integer(bounds=(0, max )),
            "nng": Integer(bounds=(0, max )),
            "npe": Integer(bounds=(0, max )),
            "nco": Integer(bounds=(0, max )),
            "nw": Integer(bounds=(0, max )),
            "nso": Integer(bounds=(0, max )),

           
        }
        super().__init__(vars=vars, n_obj=3, n_ieq_constr=2, **kwargs)
    def _evaluate(self, X, out, *args, **kwargs):
        nnu, nhydro, nng, npe, nco, nw, nso = X["nnu"], X["nhydro"], X["nng"], X["npe"], X["nco"], X["nw"], X["nso"] 

        f1 = -1*(pco*nco +pw*nw +pso*nso + pnu*nnu +phydro*nhydro +png*nng + ppe*npe ) 
        f2 =  (ecco*nco +ecw*nw +ecso*nso + ecnu*nnu +echydro*nhydro +ecng*nng + ecpe*npe ) 
        f3 =  (enco*nco +enw*nw +enso*nso + ennu*nnu +enhydro*nhydro +enng*nng + enpe*npe ) 

        g1  = f1-Power1
        #g2  = phydro+pw+pso -0.30*Power1
        g2  = Power1+Power2-f1

        out["F"] = [f1, f2, f3 ]
        out["G"]=  [g1 ,g2]

from pymoo.visualization.scatter import Scatter
from pymoo.algorithms.moo.nsga2 import NSGA2, RankAndCrowdingSurvival
from pymoo.core.mixed import MixedVariableMating, MixedVariableGA, MixedVariableSampling, MixedVariableDuplicateElimination
from pymoo.optimize import minimize
problem=MultiObjectiveMixedVariableProblem()
algorithm = NSGA2(pop_size=50,
                  sampling=MixedVariableSampling(),
                  mating=MixedVariableMating(eliminate_duplicates=MixedVariableDuplicateElimination()),
                  eliminate_duplicates=MixedVariableDuplicateElimination(),
                  )
res = minimize(problem,
               algorithm,
               ('n_gen', 100),
               seed=1,
               verbose=False)



#plot = Scatter()
#plot.add(problem.pareto_front())
#plot.add(res.F, facecolor="none", edgecolor="red")
#plot.show()

!pip install plotly

print(res.X)

print(res.F)

import plotly.express as px
import plotly.graph_objects as go

import pandas as pd
df = res.F
dict = {'power':df[:,0],
        'economic':df[:,1],
        'environmental':df[:,2]
       }
dataf = pd.DataFrame(dict)
  
display(dataf)
fig = px.scatter_3d( x=df[:,0], y=df[:,1], z=df[:,2])

fig.show()

import plotly.express as px

fig = px.scatter_3d(dataf, x='power', y='economic', z='environmental')
fig.show()

import numpy as np
weights = np.array([0.1, 0.6, 0.3])
from pymoo.decomposition.asf import ASF
import plotly.graph_objects as go
import numpy as np
decomp = ASF()
i = decomp.do(df, 1/weights).argmin()
print("Best regarding ASF: Point \ni = %s\nF = %s" % (i, df[i]))

from pymoo.visualization.scatter import Scatter
from pymoo.algorithms.moo.nsga2 import RankAndCrowdingSurvival
from pymoo.core.mixed import MixedVariableGA
from pymoo.optimize import minimize

problem = MultiObjectiveMixedVariableProblem()

algorithm = MixedVariableGA(pop_size=50, survival=RankAndCrowdingSurvival())

res = minimize(problem,
               algorithm,
               ('n_gen', 50),
               seed=1,
               verbose=False)

import pandas as pd
df = res.F
dict = {'power':df[:,0],
        'economic':df[:,1],
        'environmental':df[:,2]
       }
dataf = pd.DataFrame(dict)
  
display(dataf)
fig = px.scatter_3d(dataf, x='power', y='economic', z='environmental')
fig.show()

import numpy as np
weights = np.array([0.1, 0.6, 0.3])
from pymoo.decomposition.asf import ASF
import plotly.graph_objects as go
import numpy as np
decomp = ASF()
i = decomp.do(df, 1/weights).argmin()
print("Best regarding ASF: Point \ni = %s\nF = %s" % (i, df[i]))
import pandas as pd
dans = df[5,:]
print(dans)
fig = px.scatter_3d( x=[-7.20848904e+06], y=[2.19949925e+14], z=[1.34983988e+19])

fig.show()
#fig.show()

print(res.X[i])